#:kivy 2.0.0
#:import MapView kivy_garden.mapview.MapView
#:import GpsBlinker gpsblinker.GpsBlinker
#:include gpsblinker.kv

<TopSpotMap>:
    lat: 52.51625163358924
    lon: 13.377699466276058
    zoom: 14
    on_zoom:
        self.zoom = 4 if self.zoom < 4 else self.zoom
    on_lat:
        self.start_getting_spots_in_fov()
    on_lon:
        self.start_getting_spots_in_fov()
    GpsBlinker:
        id: blinker